services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      DATABASE_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - './.data/postgres:/var/lib/postgresql/data'
