#!/usr/bin/env bash

# PRODUCTIVITY
open "https://atom.io/"
open "https://www.google.com/intl/en-US/chrome/browser/"
open "http://www.mozilla.org/en-US/firefox/new/"
open "http://www.sublimetext.com/"
open "http://www.skype.com/en/download-skype/skype-for-computer/"
open "http://www.airsquirrels.com/reflector/download/"
open "http://pencil.evolus.vn/"
open "https://www.adobe.com/account/account-orders.html"
open "https://www.virtualbox.org/wiki/Downloads"
open "https://www.modern.ie/en-us/virtualization-tools#downloads"
open "https://www.microsoftstore.com/store/msusa/en_US/DisplayDownloadHistoryPage/"

# GAMES
open "https://minecraft.net/download"
open "https://us.battle.net/account/download/"
open "http://signup.leagueoflegends.com/en/signup/redownload"
open "http://store.steampowered.com/about/"

# INSTALL HOMEBREW
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
