#!/usr/bin/env bash

./reset-dotfiles

ln -s ~/.dotfiles/.atom ~/.atom
ln -s ~/.dotfiles/.aliases ~/.aliases
ln -s ~/.dotfiles/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/.git-completion ~/.git-completion
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/.brewfile ~/.brewfile
