#!/usr/bin/env bash

sudo -v
# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

read -p "Press [Enter] to link .dotfiles..."
./scripts/link-dotfiles
read -p "Press [Enter] to install brew stuff..."
./scripts/brew
read -p "Press [Enter] to install cask stuff..."
./scripts/cask
read -p "Press [Enter] to install node stuff..."
./scripts/node
read -p "Press [Enter] to initialize some cool settings..."
./scripts/settings

