#!/usr/bin/env bash

read -e -p "Path to Backup from: " DIRECTORY
read -e -p "Path to ~: " HOME

if [ ! -d "$DIRECTORY" ]; then
  echo "$DIRECTORY is not a valid directory"
  exit
fi

if [ ! -d "$HOME" ]; then
  echo "$HOME is not a valid directory"
  exit
fi

echo "Copying ~/.ssh"
cp -r "$DIRECTORY"/.ssh "$HOME"

echo "Copying ~/Code"
cp -r "$DIRECTORY"/Code "$HOME"

echo "Copying ~/Documents"
cp -r "$DIRECTORY"/Documents "$HOME"

echo "Copying ~/Pictures"
cp -r "$DIRECTORY"/Pictures "$HOME"

echo "Copying ~/Music"
cp -r "$DIRECTORY"/Music "$HOME"

echo "Copying Warcraft III"
cp -r "$DIRECTORY"/Warcraft\ III /Applications

echo "Copying Minecraft Saves"
mkdir -p "$HOME"/Library/Application\ Support/minecraft/saves
cp -r "$DIRECTORY"/saves "$HOME"/Library/Application\ Support/minecraft/

echo "done!"
