#!/usr/bin/env bash

read -e -p "Path to Backup from: " DIRECTORY

if [ ! -d "$DIRECTORY" ]; then
  echo "$DIRECTORY is not a valid directory"
  exit
fi

# Add /backup to the end of the directory
DIRECTORY="$DIRECTORY"/backup

# remove any duplicate / from the path for visual reasons
DIRECTORY=${DIRECTORY//\/\//\/}

if [ ! -d "$HOME" ]; then
  echo "$HOME is not a valid directory"
  exit
fi

echo "Copying ~/.ssh"
rsync -rv "$DIRECTORY"/.ssh "$HOME"

echo "Copying ~/Code"
rsync -rv "$DIRECTORY"/Code "$HOME"

echo "Copying ~/Documents"
rsync -rv "$DIRECTORY"/Documents/ "$HOME"/Documents

echo "Copying ~/Pictures"
rsync -rv "$DIRECTORY"/Pictures/ "$HOME"/Pictures

echo "Copying ~/Music"
rsync -rv "$DIRECTORY"/Music/ "$HOME"/Music

echo "Copying Warcraft III"
rsync -rv "$DIRECTORY"/Warcraft\ III /Applications

echo "Copying Minecraft Saves"
mkdir -p "$HOME"/Library/Application\ Support/minecraft/saves
rsync -rv "$DIRECTORY"/saves "$HOME"/Library/Application\ Support/minecraft/

echo "done!"
