#!/usr/bin/env bash

read -e -p "Path to Backup to: " DIRECTORY

if [ ! -d "$DIRECTORY" ]; then
  echo "$DIRECTORY is not a valid directory"
  exit
fi

echo "Copying ~/.ssh"
cp -r ~/.ssh "$DIRECTORY"

echo "Copying ~/Code"
cp -r ~/Code "$DIRECTORY"

echo "Copying ~/Documents"
cp -r ~/Documents "$DIRECTORY"

echo "Copying ~/Pictures"
cp -r ~/Pictures "$DIRECTORY"

echo "Copying ~/Music"
cp -r ~/Music "$DIRECTORY"

echo "Copying Warcraft III"
cp -r /Applications/Warcraft\ III/ "$DIRECTORY"

echo "Copying Minecraft Saves"
cp -r ~/Library/Application\ Support/minecraft/saves/ "$DIRECTORY"

echo "done!"
