#!/usr/bin/env bash

read -e -p "Volume to Backup to: " DIRECTORY

if [ ! -d "$DIRECTORY" ]; then
  echo "$DIRECTORY is not a valid directory"
  exit
fi

# Add /backup to the end of the directory
DIRECTORY="$DIRECTORY"/backup

# remove any duplicate / from the path for visual reasons
DIRECTORY=${DIRECTORY//\/\//\/}

echo "Copying ~/.dotfiles"
rm ~/.dotfiles/.atom/.atom
rsync -rv --exclude=*.DS_Store --exclude=.atom/.node-gyp --exclude=.atom/compile-cache --exclude=.atom/packages --exclude=.atom/storage ~/.dotfiles "$DIRECTORY"

echo "Copying ~/.ssh"
rsync -rv --exclude=*.DS_Store ~/.ssh "$DIRECTORY"

echo "Copying ~/Code"
rsync -rv --exclude=*.DS_Store --exclude=*/node_modules --exclude=*/bower_components ~/Code "$DIRECTORY"

echo "Copying ~/Documents"
rsync -rv --exclude=*.DS_Store ~/Documents "$DIRECTORY"

echo "Copying ~/Pictures"
rsync -rv --exclude=*.DS_Store ~/Pictures "$DIRECTORY"

echo "Copying ~/Music"
rsync -rv --exclude=*.DS_Store ~/Music "$DIRECTORY"

echo "Copying Warcraft III"
rsync -rv --exclude=*.DS_Store /Applications/Warcraft\ III "$DIRECTORY"

echo "Copying Minecraft Saves"
rsync -rv --exclude=*.DS_Store ~/Library/Application\ Support/minecraft/saves "$DIRECTORY"

echo "done!"
