#!/usr/bin/env bash

# brew setup
# ----------
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

read -p "Press [Enter] after brew has successfully installed..."

brew doctor
brew update
brew upgrade `brew outdated`
brew cleanup

echo "Installing brew stuff..."

brew install git
brew install mongodb
brew install redis
brew install trash
brew install go
brew install n
brew install wget
brew install heroku-toolbelt
brew install caskroom/cask/brew-cask

brew doctor
brew update
brew upgrade `brew outdated`
brew cleanup

# Post install GitConfig setup
# ----------------------------
git update-index --assume-unchanged .gitconfig
read -e -p "git username: " GIT_USER
read -e -p "git email: " GIT_EMAIL
git config --global user.name "$GIT_USER"
git config --global user.email "$GIT_EMAIL"
