#!/usr/bin/env bash

# brew setup
# ----------
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

read -p "Press [Enter] after brew has successfully installed..."

brew doctor
brew update
brew upgrade `brew outdated`
brew cleanup

echo "Installing brew stuff..."

brew install git
brew install mongodb
brew install postgres
brew install redis
brew install trash
brew install go
brew install nvm
brew install wget
brew install tree
brew install docker
brew install boot2docker
brew install caskroom/cask/brew-cask

brew doctor
brew update
brew upgrade `brew outdated`
brew cleanup

# Load mongodb automatically
# ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
# launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist

# Load postres automatically
# ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
# launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

# Load redis automatically
# ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
# launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
