#!/usr/bin/env bash

# cask setup
# ----------
apps=(
  atom
  battle-net
  discord
  firefox
  google-chrome
  league-of-legends
  macid
  mamp
  minecraft
  sequel-pro
  sketch
  skype
  slack
  spacemonkey
  steam
  virtualbox
  visual-studio-code
)

echo "Installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}

# Atom specific setup
apm stars --install
