#!/usr/bin/env bash

# cask setup
# ----------
apps=(
  google-chrome
  firefox
  atom
  skype
  steam
  league-of-legends
  minecraft
  sequel-pro
  mamp
  silverlight
  virtualbox
)

echo "Installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}

# Atom specific setup
apm stars --install
