#!/usr/bin/env bash

# Remove existing dotfiles
# ------------------------
[[ -r ~/.atom ]]           && rm ~/.atom
[[ -r ~/.bash_profile ]]   && rm ~/.bash_profile
[[ -r ~/.gitconfig ]]      && rm ~/.gitconfig
[[ -r ~/.inputrc ]]        && rm ~/.inputrc

# Symlink dotfiles
# ----------------
ln -s ~/.dotfiles/.atom ~/.atom
ln -s ~/.dotfiles/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.inputrc ~/.inputrc

# Symlink plist files
# http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/#Mac-OS-X
# -------------------
ln -s ~/.dotfiles/files/limit.maxfiles.plist /Library/LaunchDaemons/limit.maxfiles.plist
ln -s ~/.dotfiles/files/limit.maxproc.plist /Library/LaunchDaemons/limit.maxproc.plist
