#!/usr/bin/env bash

# Remove existing dotfiles
# ------------------------
rm ~/.atom
rm ~/.bash_profile
rm ~/.gitconfig
rm ~/.inputrc

# Symlink dotfiles
# ----------------
ln -s ~/.dotfiles/config/.atom ~/.atom
ln -s ~/.dotfiles/config/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/config/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/config/.inputrc ~/.inputrc
