#!/usr/bin/env bash

# Remove existing dotfiles
# ------------------------
[[ -r ~/.atom ]]         && rm ~/.atom
[[ -r ~/.bash_profile ]] && rm ~/.bash_profile
[[ -r ~/.gitconfig ]]    && rm ~/.gitconfig
[[ -r ~/.inputrc ]]      && rm ~/.inputrc

# Symlink dotfiles
# ----------------
ln -s ~/.dotfiles/config/.atom ~/.atom
ln -s ~/.dotfiles/config/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/config/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/config/.inputrc ~/.inputrc
