#!/usr/bin/env bash

n latest
n stable

mkdir ~/.npm
sudo chown -R `whoami` ~/.npm
sudo chown -R `whoami` /usr/local

npm install -g npm
npm install -g travis-encrypt
npm install -g slush
npm install -g gulp
npm install -g bower

