#!/usr/bin/env bash

nvm install stable
nvm alias default `nvm current`

mkdir ~/.npm
mkdir ~/.nvm

sudo chown -R `whoami` ~/.npm
sudo chown -R `whoami` /usr/local

npm adduser

npm install -g npm

npm install -g `npm stars`
