#!/usr/bin/env bash

n latest
n stable

mkdir ~/.npm
sudo chown -R `whoami` ~/.npm
sudo chown -R `whoami` /usr/local/lib/node_modules

npm install -g travis-encrypt slush mocha jshint gulp grunt-cli bower
