#!/usr/bin/env bash

################################################################################
# DEFAULTS
################################################################################

# Makes window resize time instant
defaults write -g NSWindowResizeTime -float 0.003

################################################################################
# Set zsh as the shell
################################################################################
# sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells"
# chsh -s /usr/local/bin/zsh

################################################################################
# Kill affected applications
################################################################################

# Do a restart instead
echo ""
echo "Restart your computer when you get a chance"
