#!/usr/bin/env bash

mkdir ~/tmp_vms
cd ~/tmp_vms

# https://www.modern.ie/en-us/virtualization-tools
# IE 7 on Windows Vista
curl -O -L "https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS=IE7-Vista&parts=4&filename=VMBuild_20131127/VirtualBox/IE7_Vista/Mac/IE7.Vista.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
# IE 8 on Windows 7
curl -O -L "https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS=IE8-Win7&parts=4&filename=VMBuild_20131127/VirtualBox/IE8_Win7/Mac/IE8.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
# IE 9 on Windows 7
curl -O -L "https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS=IE9-Win7&parts=4&filename=VMBuild_20131127/VirtualBox/IE9_Win7/Mac/IE9.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
# IE 10 on Windows 7
curl -O -L "https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS=IE10-Win7&parts=4&filename=VMBuild_20131127/VirtualBox/IE10_Win7/Mac/IE10.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
# IE 11 on Windows 7
curl -O -L "https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS=IE11-Win7&parts=4&filename=VMBuild_20131127/VirtualBox/IE11_Win7/Mac/IE11.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"

# change permissions on .sfx
chmod a+x *.sfx
# run .sfx
for i in *.sfx; do
  ./$i;
done
# remove source files
rm *.sfx *.rar
# open all of the .ovas with VirtualBox
for i in *.ova; do
  open -a /Applications/VirtualBox.app "$i";
done
# wait until everything's been imported
read -p "Press [Enter] after importing..."
# delete tmp folder
cd ~
rm -rf ~/tmp_vms
