[tools]
bun = "latest"
deno = "latest"
go = "latest"
terraform = "latest"
node = "latest"
erlang = "latest"
elixir = "latest"
python = "latest"
pipx = "latest"

[settings]
disable_hints = ["outdated_bump"]
