[tools]
bun = "latest"
deno = "latest"
go = "latest"
terraform = "latest"
node = "latest"
erlang = "latest"
elixir = "latest"
pipx = "latest"
caddy = "latest"
rust = "latest"
pnpm = "latest"

[settings]
disable_hints = ["outdated_bump"]
idiomatic_version_file_enable_tools = ["node"]
